version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: tree_grower_db
    restart: unless-stopped
    # TODO: move all envs to file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: nikog23/kiii_tree_grower:latest
    container_name: tree_grower_app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata: