version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

  app:
    build: .
    image: nikog23/kiii_tree_grower:latest
    container_name: tree_grower_app
    restart: unless-stopped
    env_file:
      - .env  
    depends_on:
      - db
    ports:
      - "8000:80"


volumes:
  pgdata: