apiVersion: v1
kind: ConfigMap
metadata:
  name: tree-grower-postgres-config
  namespace: kiii
data:
  POSTGRES_DB: tree_grower_db
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: tree-grower-postgres-secret
  namespace: kiii
type: Opaque
data:
  POSTGRES_PASSWORD: "YWp2YXIgc28gc2lyZW5qZQ=="  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tree-grower-postgres-pvc
  namespace: kiii
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tree-grower-postgres
  namespace: kiii
spec:
  serviceName: tree-grower-postgres-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: kiii
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: tree-grower-postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tree-grower-postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: tree-grower-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: tree-grower-postgres-data
          persistentVolumeClaim:
            claimName: tree-grower-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-tree-grower-service
  namespace: kiii
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
